config/routes.rb
CwruUsg::Application.routes.draw do
  get "welcome/index"
  get "users/login"
  get "users/logout"

  resources :groups
  resources :slider_images
  
  match 'page/:name' => "admin/pages#show", :via=>:get, :as => :page

  get "admin", :controller=>"admin/home", :action=>"index"
  namespace :admin do
    resources :gas
    resources :pages
  end
  
  match 'committee/:id' => "group#show"

  root :to => 'welcome#index'

end

app/models/ga.rb
class Ga < ActiveRecord::Base
  validates_uniqueness_of :date
  validates_presence_of :date

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user  
end

app/models/slider_image.rb
class SliderImage < ActiveRecord::Base
  has_attached_file :image, {
    :styles => { :full => "589x279!", :thumb => "211x100#" },
    :url => ":rails_root/public/system/:attachment/:id/:style/:hash.:extension",
    :hash_secret => "WhatACoolS3cr3tStr1ngAb0u7U5G"
  }
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  validates_presence_of :title
  validates_format_of :slug, :with => /[A-Za-z-_]*/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :groups, :foreign_key => :vp_id
end

app/controllers/admin/gas_controller.rb
class Admin::GasController < ApplicationController
  before_filter :is_admin 
  before_filter :breadcrumb

  def index
    @gas = Ga.find(:all, :order=>"date DESC")
  end

  def show
    @ga = Ga.find(params[:id])

  end

  def create
    @new_ga = Ga.new(params[:ga])
    if !@new_ga.save
      flash[:error] = @new_ga.errors.full_messages.first
    end
    redirect_to :admin_gas
  end

  def update
    @ga = Ga.find(params[:id])
    if !@ga.update_attributes(params[:ga])
      flash[:error] = @ga.errors.full_messages.first
    end

    redirect_to :admin_gas
  end

  def new
    breadcrumbs.add("New")
    @ga = Ga.new
    @last = Ga.find(:first, :order => "date DESC")

  end

  def edit
    breadcrumbs.add("Edit")
    @ga = Ga.find(params[:id])
  end

  def destroy
    @ga = Ga.find(params[:id])
    @ga.delete

    redirect_to :admin_gas
  end

  def breadcrumb
    breadcrumbs.add("GAs", admin_gas_url)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :setup

  def setup
    @user = User.find_by_case_id(session[:cas_user]) if session[:cas_user]
    @user ||= nil

    breadcrumbs.add("Home", root_url)
  end

  def is_admin
    breadcrumbs.add("Admin", admin_url)
    return redirect_to(users_login_url) unless @user
    if !@user.is_admin
      return redirect_to(welcome_index_url)
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
    @groups = Group.all
  end
  
  def show
    @group = Group.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @pages = StaticPage.all
  end

  def create
    @page = StaticPage.new(params[:static_page])
    if !@page.save
      flash[:error] = @page.errors.full_messages.first
    end

    redirect_to admin_pages_url
  end

  def update
    @page = StaticPage.find(params[:id])
    if !@page.update_attributes(params[:static_page])
      flash[:error] = "Could not update! #{@page.errors.full_messages.first}"
    end

    redirect_to admin_pages_url
  end

  def new
    @page = StaticPage.new
  end

  def edit
    @page = StaticPage.find(params[:id])
  end

  def show
    @page = StaticPage.find(params[:id]) if params[:id]
    @page = StaticPage.find_by_slug(params[:name]) if params[:name]
  end

  def destroy
    @page = StaticPage.find(params[:id])
    if !@page.destroy
      flash[:error] = "Could not destroy page!"
    end

    redirect_to admin_pages_url
  end

end

app/controllers/slider_images_controller.rb
class SliderImagesController < ApplicationController
  def index
    @slider_images = SliderImage.all
  end

  def new
    @slider_image = SliderImage.new
  end
  
  def create
    @slider_image = SliderImage.new(params[:slider_image])
    
    if @slider_image.save
      redirect_to slider_images_url
    else
      render :action => 'new'
    end
  end
  
  def destory
    @slider_image = SliderImage.find(params[:id])
    @slider_image.destory
    
    redirect_to slider_images_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter, :only => [:login]

  def login
    u = User.find_or_create_by_case_id(session[:cas_user])
    redirect_to welcome_index_url
  end

  def logout
    session.delete(:cas_user)
    redirect_to welcome_index_url
  end

  def show
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @slider_images = SliderImage.all
    render :index, :layout => "homepage"
  end
end

app/helpers/admin/gas_helper.rb
module Admin::GasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/slider_image_helper.rb
module SliderImageHelper
end

app/helpers/slider_images_helper.rb
module SliderImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.haml
%footer#footer
  - if controller.controller_name == "welcome"
    :javascript
      $(window).load(function() {
        $('#slider').nivoSlider();
      });
  #container
    =link_to "Log In", users_login_url

app/views/layouts/_header.html.haml
%head
  %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
  %title Undergraduate Student Government - USG
  %link{:href=>'http://fonts.googleapis.com/css?family=Habibi',:rel=>'stylesheet',:type=>'text/css'}
  = stylesheet_link_tag "application"
  = javascript_include_tag "application"
  - if is_home_page
    = javascript_include_tag "nivo-slider"
  = csrf_meta_tag
  :javascript
    $(function(){
      $("body").noisy({
        opacity: 0.07
      });
    });      

app/views/layouts/_toplinks.html.haml
%ul
  %li
    %a{:href => "#"} Resources
  %li
    %a{:href => "#"} About USG
    %ul.sub-menu
      %li
        %a{:href=>"#"} Something One
      %li
        %a{:href=>"#"} Something Two
      %li
        %a{:href=>"#"} Something Three
      %li
        %a{:href=>"#"} Something Four
      %li
        %a{:href=>"#"} Something Five
  - if @user && @user.is_admin
    %li
      %a{:href=>"#"}=(@user.name || @user.case_id)
      %ul.sub-menu
        %li
          %a{:href=>admin_gas_url} General Assemblies
        %li
          %a{:href=>admin_pages_url} Pages
        %li
          %a{:href=>users_logout_url} Log Out

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  = render :partial=> "layouts/header", :locals => {:is_home_page => false}
  %body
    %header#header-small
      #container
        #logo
          %a{:href=>welcome_index_url}
            =image_tag "logo.png", :class=>"logo"
        #navigation
          =render :partial=>"layouts/toplinks"
    #container.top-bar-small
      #right
        %h1
          Undergraduate Student Government
        %div.breadcrumbs
          =breadcrumbs.render(:format=> :usg, :separator => "→")
    #container.content.subpage
      =yield
    = render :partial=>"layouts/footer"

app/views/layouts/homepage.html.haml
!!! 5
%html{:lang => "en"}
  = render :partial=>"layouts/header", :locals => {:is_home_page => true}
  %body
    %header#header
      #container
        #logo
          =image_tag "logo.png", :class=>"logo"
          %h1 Undergraduate Student Government
          %ul
            %li 
              %a{:href=>"#"} Feedback Form →
            %li 
              %a{:href=>"#"} Submit a Disbursement →
            %li
              %a{:href=>"#"} Search → 
        #navigation
          = render :partial => "layouts/toplinks"
    #container.top-bar
      #right
        .slider-wrapper
          #slider.nivo-slider
            - @slider_images.each do |slider_image|
              =image_tag slider_image.image.url(:full)
    #container.content
      =yield
    = render :partial => "layouts/footer"

app/views/pages/_pageform.html.haml
- if page.new_record?
  - title="New Static Content Page"
  - url=admin_pages_url
  - method="POST"
- else
  - title="Edit Content Page -- #{page.title}"
  - url=admin_page_url(page)
  - method="PUT"
=javascript_include_tag "https://raw.github.com/coreyti/showdown/master/src/showdown.js"
:javascript
  $(function() {
    var c = new Showdown.converter();
    $("textarea#static_page_contents").keyup(function() {
      $("td#renderings").html( c.makeHtml(this.value) );
    });
  });
%h1=title
%table
  %tbody
    %tr
      %td{:style=>"width:15%"}
        =form_for(page, :url=>url, :method=>method) do |f|
          %p=f.label :title, "Page Title:"
          =f.text_field :title
          %p=f.label :slug, "Page Slug:"
          =f.text_field :slug
          %p Note: The slug is a single word which points to this page. Only letters, hyphens, and underscores are permitted. For example, the "About USG" page might have a slug of "about-usg".
          %p=f.label :contents, "Page Contents:"
          =f.text_area :contents,:rows=>20, :cols=>35
          =f.submit "Create Page!"
      %td#renderings{:style=>"width:85%"}
        - if page.contents
          !=BlueCloth.new(page.contents).to_html
        - else
          %p 
            A live preview of the site will occur here as you type in the box. You may format text using  
            %a{:href=>"http://en.wikipedia.org/wiki/Markdown",:target=>"_new"} Markdown syntax.

app/views/pages/create.html.haml
%h1 Pages#create
%p Find me in app/views/pages/create.html.haml

app/views/pages/edit.html.haml
= render :partial=>"pageform", :locals => {:page=>@page}

app/views/pages/index.html.haml
%h1 Static Content Pages
%table
  %thead
    %th Page Title
    %th Page Slug
    %th Edit
    %th Delete
  %tbody
    - @pages.each do |p|
      %tr
        %td
          %p=p.title
        %td
          %p=p.slug
        %td
          %p=link_to "Edit", edit_admin_page_url(p)
        %td
          %p=link_to "Delete", admin_page_url(p), :method=>"DELETE"
%h2
  =link_to "Make one!", new_admin_page_url

app/views/pages/list.html.haml
%h1 Pages#list
%p Find me in app/views/pages/list.html.haml

app/views/pages/new.html.haml
=javascript_include_tag "https://raw.github.com/coreyti/showdown/master/src/showdown.js"
:javascript
  $(function() {
    var c = new Showdown.converter();
    $("textarea#static_page_contents").keyup(function() {
      $("td#renderings").html( c.makeHtml(this.value) );
    });
  });
%h1 New Static Content Page
=form_for(@page, :url=>admin_pages_url) do |f|
  %p=f.label :title, "Page Title:"
  =f.text_field :title
  %table
    %thead
      %th{:style=>"width:15%"}=f.label :contents, "Content:"
      %th{:style=>"width:85%"}
        %label Rendered:
    %tbody
      %tr
        %td=f.text_area :contents,:rows=>20, :cols=>35
        %td#renderings
          %p 
            A live preview of the site will occur here as you type in the box. You may format text using  
            %a{:href=>"http://en.wikipedia.org/wiki/Markdown",:target=>"_new"} Markdown syntax.
  =f.submit "Create Page!"

app/views/pages/show.html.haml
!=BlueCloth.new(@page.contents).to_html