config/routes.rb
CwruUsg::Application.routes.draw do
  get "welcome/index"
  get "users/login"
  get "users/logout"

  resources :groups
  resources :slider_images
  
  match 'page/:name' => "admin/pages#show", :via=>:get, :as => :page

  get "admin", :controller=>"admin/home", :action=>"index"
  namespace :admin do
    resources :gas
    resources :pages
  end
  
  match 'committee/:id' => "group#show"

  root :to => 'welcome#index'

end

app/models/ga.rb
class Ga < ActiveRecord::Base
  validates_uniqueness_of :date
  validates_presence_of :date

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user  
end

app/models/slider_image.rb
class SliderImage < ActiveRecord::Base
  has_attached_file :image, {
    :styles => { :full => "589x279!", :thumb => "211x100#" },
    :url => ":rails_root/public/system/:attachment/:id/:style/:hash.:extension",
    :hash_secret => "WhatACoolS3cr3tStr1ngAb0u7U5G"
  }
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  validates_presence_of :title
  validates_format_of :slug, :with => /[A-Za-z-_]*/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :groups, :foreign_key => :vp_id
end

app/controllers/admin/gas_controller.rb
class Admin::GasController < ApplicationController
  before_filter :is_admin 
  before_filter :breadcrumb

  def index
    @gas = Ga.find(:all, :order=>"date DESC")
  end

  def show
    @ga = Ga.find(params[:id])

  end

  def create
    @new_ga = Ga.new(params[:ga])
    if !@new_ga.save
      flash[:error] = @new_ga.errors.full_messages.first
    end
    redirect_to :admin_gas
  end

  def update
    @ga = Ga.find(params[:id])
    if !@ga.update_attributes(params[:ga])
      flash[:error] = @ga.errors.full_messages.first
    end

    redirect_to :admin_gas
  end

  def new
    breadcrumbs.add("New")
    @ga = Ga.new
    @last = Ga.find(:first, :order => "date DESC")

  end

  def edit
    breadcrumbs.add("Edit")
    @ga = Ga.find(params[:id])
  end

  def destroy
    @ga = Ga.find(params[:id])
    @ga.delete

    redirect_to :admin_gas
  end

  def breadcrumb
    breadcrumbs.add("GAs", admin_gas_url)
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_filter :is_admin

  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :setup

  def setup
    @user = User.find_by_case_id(session[:cas_user]) if session[:cas_user]
    @user ||= nil

    breadcrumbs.add("Home", root_url)
  end

  def is_admin
    breadcrumbs.add("Admin", admin_url)
    return redirect_to(users_login_url) unless @user
    if !@user.is_admin
      return redirect_to(welcome_index_url)
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
    @groups = Group.all
  end
  
  def show
    @group = Group.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @pages = StaticPage.all
  end

  def create
    @page = StaticPage.new(params[:static_page])
    if !@page.save
      flash[:error] = @page.errors.full_messages.first
    end

    redirect_to admin_pages_url
  end

  def update
    @page = StaticPage.find(params[:id])
    if !@page.update_attributes(params[:static_page])
      flash[:error] = "Could not update! #{@page.errors.full_messages.first}"
    end

    redirect_to admin_pages_url
  end

  def new
    @page = StaticPage.new
  end

  def edit
    @page = StaticPage.find(params[:id])
  end

  def show
    @page = StaticPage.find(params[:id]) if params[:id]
    @page = StaticPage.find_by_slug(params[:name]) if params[:name]
  end

  def destroy
    @page = StaticPage.find(params[:id])
    if !@page.destroy
      flash[:error] = "Could not destroy page!"
    end

    redirect_to admin_pages_url
  end

end

app/controllers/slider_images_controller.rb
class SliderImagesController < ApplicationController
  def index
    @slider_images = SliderImage.all
  end

  def new
    @slider_image = SliderImage.new
  end
  
  def create
    @slider_image = SliderImage.new(params[:slider_image])
    
    if @slider_image.save
      redirect_to slider_images_url
    else
      render :action => 'new'
    end
  end
  
  def destory
    @slider_image = SliderImage.find(params[:id])
    @slider_image.destory
    
    redirect_to slider_images_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter, :only => [:login]

  def login
    u = User.find_or_create_by_case_id(session[:cas_user])
    redirect_to welcome_index_url
  end

  def logout
    session.delete(:cas_user)
    redirect_to welcome_index_url
  end

  def show
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @slider_images = SliderImage.all
    render :index, :layout => "homepage"
  end
end

app/helpers/admin/gas_helper.rb
module Admin::GasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/slider_image_helper.rb
module SliderImageHelper
end

app/helpers/slider_images_helper.rb
module SliderImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/gas/_ga_form.html.haml
- if @ga.new_record?
  - method = "POST"
  - path = admin_gas_url
- else
  - method = "PUT"
  - path = admin_ga_url(@ga)
=form_for(@ga, :url=>path, :method=>method) do |f|
  %p Date:
  =f.date_select :date, :default => (@ga.date || (@last.date + 7.days))
  %p Video Embed Code:
  =f.text_area :video, :style=>"height:50px"
  %p Notes:
  =f.text_area :notes
  %br
  =f.submit

app/views/admin/gas/edit.html.haml
%h1 Edit GA
= render :partial => "ga_form"

app/views/admin/gas/index.html.haml
%h1 List of GAs:
%table
  %thead
    %th GA Date
    %th Minutes
    %th Agenda
    %th Edit
    %th Delete
  %tbody 
    -@gas.each do |g|
      %tr
        %td
          %p=g.date
        %td
          %p=g.minutes_id
        %td
          %p=g.agenda_id
        %td
          %p=link_to "Edit", edit_admin_ga_url(g.id)
        %td
          %p=link_to "Delete", admin_ga_url(g.id), :method=>:delete
%h2=link_to "New GA", new_admin_ga_url

app/views/admin/gas/new.html.haml
%h1 New GA
=form_for(@ga, :url=>admin_gas_url) do |f|
  %p Date:
  =f.date_select :date
  %br
  %br
  =f.submit
  %p Add more fields later...

app/views/admin/home/index.html.haml
%h1 Admin Control Panel
%h2
  %a{:href=>admin_gas_url} General Assemblies

app/views/groups/index.html.haml
-@groups.each do |g|
  =g.inspect

app/views/groups/show.html.haml
=@group.inspect

app/views/slider_images/index.html.haml
%h1 SliderImages#index
%p Find me in app/views/slider_images/index.html.haml
-@slider_images.each do |slider_image|
	%p= image_tag slider_image.image.url(:full)
	%p= slider_image.inspect

app/views/slider_images/new.html.haml
%h1 Add a slider image
=form_for @slider_image do |f|
	=f.error_messages
	%p
		=f.label :image, 'Image file:'
		=f.file_field :image
	%p
		=f.submit

app/views/users/logout.html.erb
<h1>Users#logout</h1>
<p>Find me in app/views/users/logout.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/index.html.haml
#ga
  %h1 Last Week in USG...
  #video
    %iframe{:allowfullscreen => "", :frameborder => "0", :height => "180", :src => "http://www.youtube.com/embed/TgMg_ZiHN8g", :width => "240"}
  %h2 November 8, 2011
  %ul#top-three
    %li 
      %a{:href=>"#"} Agenda →
    %li 
      %a{:href=>"#"} Minutes →
    %li 
      %a{:href=>"#"} Voting Record →
  %ul#bottom-two
    %li
      %a{:href=>"#"} Committees
    %li 
      %a{:href=>"#"} Caucuses

#events
  %h1 Upcoming Events
  %div.event
    %h2 New USG website!
    %p The USG website is due to launch in 2012!  Woo! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sapien sem, iaculis vel pulvinar eu, viverra id ante.
    %span.group Undergraduate Student Government
  %div.event
    %h2 Frisbee Tournament
    %p The only other thing I could think of. Nullam cursus dolor id nisi venenatis euismod. Aenean in urna neque, a commodo nunc.
    %span.group Ultimate Frisbee Club